apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity-service.fullname" . }}
  labels:
    {{- include "identity-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "identity-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "identity-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: AUTH0_DOMAIN
              value: {{ .Values.auth0.domain | quote }}
            - name: AUTH0_AUDIENCE
              value: {{ .Values.auth0.audience | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.targetPort }}
